/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(copy_rand.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(60356deedbb2d43359111be777310f8d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <sched/copy_rand.h>
// pydoc.h is automatically generated in the build directory
#include <copy_rand_pydoc.h>

void bind_copy_rand(py::module& m)
{

    using copy_rand    = ::gr::sched::copy_rand;


    py::class_<copy_rand, gr::block, gr::basic_block,
        std::shared_ptr<copy_rand>>(m, "copy_rand", D(copy_rand))

        .def(py::init(&copy_rand::make),
           py::arg("item_size"),
           py::arg("max_copy") = 4294967295U,
           D(copy_rand,make)
        )
        



        ;




}








