/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(msg_forward.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6433a685106f8c20e5ce52004e4de7bb)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <sched/msg_forward.h>
// pydoc.h is automatically generated in the build directory
#include <msg_forward_pydoc.h>

void bind_msg_forward(py::module& m)
{

    using msg_forward    = ::gr::sched::msg_forward;


    py::class_<msg_forward, gr::block, gr::basic_block,
        std::shared_ptr<msg_forward>>(m, "msg_forward", D(msg_forward))

        .def(py::init(&msg_forward::make),
           D(msg_forward,make)
        )
        



        ;




}








